basePath: /
definitions:
  serializer.CreateItemRequest:
    properties:
      info:
        $ref: '#/definitions/serializer.ItemInfo'
    type: object
  serializer.CreateItemResponse:
    properties:
      id:
        type: integer
    type: object
  serializer.CreateListRequest:
    properties:
      info:
        $ref: '#/definitions/serializer.ListInfo'
    type: object
  serializer.CreateListResponse:
    properties:
      id:
        type: integer
    type: object
  serializer.DeleteListResponse:
    properties:
      status:
        type: string
    type: object
  serializer.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  serializer.Item:
    properties:
      create_at:
        type: string
      id:
        type: integer
      info:
        $ref: '#/definitions/serializer.ItemInfo'
      update_at:
        type: string
    type: object
  serializer.ItemInfo:
    properties:
      description:
        type: string
      done:
        type: boolean
      title:
        type: string
    type: object
  serializer.List:
    properties:
      created_at:
        type: string
      id:
        type: integer
      info:
        $ref: '#/definitions/serializer.ListInfo'
      updated_at:
        type: string
    type: object
  serializer.ListInfo:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  serializer.ListItemResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Item'
        type: array
    type: object
  serializer.ListsResponse:
    properties:
      lists:
        items:
          $ref: '#/definitions/serializer.List'
        type: array
    type: object
  serializer.SignInInfo:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  serializer.SignInRequest:
    properties:
      info:
        $ref: '#/definitions/serializer.SignInInfo'
    type: object
  serializer.SignInResponse:
    properties:
      id:
        type: integer
    type: object
  serializer.SignUpInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  serializer.SignUpRequest:
    properties:
      info:
        $ref: '#/definitions/serializer.SignUpInfo'
    type: object
  serializer.SignUpResponse:
    properties:
      token:
        type: string
    type: object
  serializer.UpdateItemInfo:
    properties:
      description:
        type: string
      done:
        type: boolean
      title:
        type: string
    type: object
  serializer.UpdateItemRequest:
    properties:
      info:
        $ref: '#/definitions/serializer.UpdateItemInfo'
    type: object
  serializer.UpdateItemResponse:
    properties:
      status:
        type: string
    type: object
  serializer.UpdateListInfo:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  serializer.UpdateListRequest:
    properties:
      info:
        $ref: '#/definitions/serializer.UpdateListInfo'
    type: object
  serializer.UpdateListResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Simple To-Do list backend
  title: GoDone API
  version: "1.0"
paths:
  /api/items/{list_id}:
    get:
      consumes:
      - application/json
      description: Get List Items
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Get List Items
      tags:
      - item
    post:
      consumes:
      - application/json
      description: Create item for to-do list
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      - description: CreateItemRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.CreateItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Create Item
      tags:
      - item
  /api/items/{list_id}/{item_id}:
    delete:
      consumes:
      - application/json
      description: Delete Item by id
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      - description: Item ID
        in: path
        name: item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.UpdateItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Delete Item by id
      tags:
      - item
    get:
      consumes:
      - application/json
      description: Get List Items
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      - description: Item ID
        in: path
        name: item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Get Item by id
      tags:
      - item
    put:
      consumes:
      - application/json
      description: Get List Items
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      - description: Item ID
        in: path
        name: item_id
        required: true
        type: string
      - description: UpdateItemRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.UpdateItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.UpdateItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Update Item by id
      tags:
      - item
  /api/lists:
    get:
      consumes:
      - application/json
      description: Get user to-do lists
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Get Lists
      tags:
      - list
    post:
      consumes:
      - application/json
      description: Create user to-do list
      parameters:
      - description: CreateListRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.CreateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Create List
      tags:
      - list
  /api/lists/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user to-do list
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.DeleteListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Delete List
      tags:
      - list
    get:
      consumes:
      - application/json
      description: Get user to-do list by id
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.CreateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Get List by id
      tags:
      - list
    put:
      consumes:
      - application/json
      description: Update user to-do list
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      - description: UpdateListRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.UpdateListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.UpdateListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: Update List
      tags:
      - list
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Sign in a user
      parameters:
      - description: SignInRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: User sign-in
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign up a user and get token
      parameters:
      - description: SignInRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.ErrorResponse'
      summary: User sign-up
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
